---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#


# install tasks file for ipst.jdk8

- name: Download jdk8
  command: "wget -q -O /tmp/{{ jdk8_archivename }} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ jdk8_url }} creates=/tmp/{{ jdk8_archivename }}"

- name: extract jdk8
  unarchive: copy=no src="/tmp/{{ jdk8_archivename }}" dest="{{ jdk8_dest_path }}" creates="{{ jdk8_prefix }}" owner=root group=root mode=0755
  register: jdk8installed

- name: Fix ownership
  file: state=directory path={{ jdk8_prefix }} owner=root group=root recurse=yes

# manage via alternative
#- name: Make Java available for system
#  command: 'alternatives --install "/usr/bin/java" "java" "{{ jdk8_prefix }}/bin/java" 2000'

- name: remove tmp
  file: state=absent path=/tmp/{{ jdk8_archivename }}

- name: add environment variables config file
  when: jdk8installed|success
  register: jdk8_envvars_config
  template: src=jdk8_env.sh.j2 dest="/etc/profile.d/jdk8_env.sh" owner=root group=root

