/** Copyright (c) 2016, Tractebel (http://www.tractebel-engie.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/.
 **/
package eu.itesla_project.cta.service;
/**
 * @author Yannick Pihan <yannick.pihan at tractebel.engie.com>
 */
public enum IpsoOutputListingMessageType {
    // ON_BOUND_CONSTRAINT
    IPSO_OUTPUT_LISTING("IPSO OUTPUT LISTING"),
    NODES_ON_BOUND_CONSTRAINT("REGULATED NODES WHERE THE VOLTAGE BOUND CONSTRAINTS ARE NOT VIOLATED"),
    Q_ON_BOUND_CONSTRAINT_REMOVED("Q BOUND CONSTRAINTS AND VARIABLE REMOVED, BECAUSE THE Q VALUE IS ON THE BOUNDS"),
    VOLTAGE_ON_BOUND_CONSTRAINT_REMOVED("RELATED VOLTAGE BOUND CONSTRAINTS REMOVED"),
    TRANSFORMER_ON_BOUND_CONSTRAINT("REGULATED TRANSFORMER WHERE THE TAP VALUE IS ON THE BOUNDS"),
    TAP_ON_BOUND_CONSTRAINT_REMOVED("TAP CONSTRAINTS AND VARIABLES REMOVED"),
    VOLTAGE_ON_BOUND_CONSTRAINT_TRANSFORMER_REMOVED("RELATED VOLTAGE CONSTRAINTS REMOVED"),
    // ...
    VIOLATED_LINE_FLOW_CONSTRAINTS_REMOVED_WITH_MIN_MAX("VIOLATED LINE FLOW CONSTRAINTS REMOVED WITH MIN < MAX"),
    VIOLATED_TRANSFORMER_FLOW_CONSTRAINTS_REMOVED_WITH_MIN_MAX("VIOLATED TRANSFORMER FLOW CONSTRAINTS REMOVED WITH MIN < MAX"),
    TRANSFORMERS_REGULATING_THE_FLOW_SUBJECT_TO_VIOLATED_BOUND_CONSTRAINTS_WITH_MIN_MAX_ARE_REMOVED("TRANSFORMERS REGULATING THE FLOW SUBJECT TO VIOLATED BOUND CONSTRAINTS WITH MIN=MAX ARE REMOVED"),
    RELATED_TAP_CONSTRAINTS_ARE_REMOVED("RELATED TAP CONSTRAINTS ARE REMOVED"),
    RELATED_TAP_VARIABLE_ARE_REMOVED("RELATED TAP VARIABLE ARE REMOVED"),
    VIOLATED_VOLTAGE_BOUND_CONSTRAINTS_REMOVED_WITH_MIN_MAX("VIOLATED VOLTAGE BOUND CONSTRAINTS REMOVED WITH MIN < MAX"),
    VIOLATED_VOLTAGE_BOUND_CONSTRAINTS_REMOVED_WITH_MIN_MAX1("VIOLATED VOLTAGE BOUND CONSTRAINTS REMOVED WITH MIN≃MAX"),
    CONNECTED_GENERATORS_REGULATING_THE_NODE_VOLTAGE_SUBJECT_TO_VIOLATED_BOUND_CONSTRAINTS_WITH_MIN_MAX("CONNECTED GENERATORS REGULATING THE NODE VOLTAGE SUBJECT TO VIOLATED BOUND CONSTRAINTS WITH MIN=MAX"),
    Q_BOUND_CONTRAINTS_AND_VARIABLE_REMOVED("Q BOUND CONTRAINTS AND VARIABLE REMOVED"),
    TRANSFORMER_REGULATING_THE_NODE_VOLTAGE_SUBJECT_TO_VIOLATED_BOUND_CONSTRAINTS_WITH_MIN_MAX("TRANSFORMER REGULATING THE NODE VOLTAGE SUBJECT TO VIOLATED BOUND CONSTRAINTS WITH MIN=MAX"),
    TRANSFORMER_TAP_BOUND_CONSTRAINTS_AND_VARIABLE_REMOVED("TRANSFORMER TAP BOUND CONSTRAINTS AND VARIABLE REMOVED"),
    // ...
    INVALID_COMPONENTS("INVALID IPSO COMPONENTS"),
    UNSUPPORTED_CORRECTIVE_ACTIONS("UNSUPPORTED CORRECTIVE ACTIONS"),
    VIOLATED_CONSTRAINTS("VIOLATED CONSTRAINTS"),
    CONTINGENCY_HEADER("CONTINGENCY APPLIED:"),
    CONTINGENCY_ARRAY_HEADER("EQUIPMENTS LOST"),
    ACTION_PLAN_FOUND("ACTION PLANS FOUND"),
    ACTION_FOUND("ACTIONS FOUND"),
    NEW_CORRECTIVE_CONTROLVARIABLES("CORRECTIVE CONTROL VARIABLES"),
    NEW_CORRECTIVE_CONSTRAINTS("CORRECTIVE CONSTRAINTS"),
    NEW_TOPOLOGICAL_ACTIONS("CORRECTIVE TOPOLOGICAL ACTIONS"),
    ASSOCIATION_FOUND("ASSOCATION FOUND"),
    NO_ASSOCIATION_FOUND("NO ASSOCIATION FOUND"),
    OBJ_FUN_VALUE("OBJECTIVE FUNCTION VALUE:"),
    SOLUTION_FOUND("SOLUTION FOUND:"),
    // AMPL
    AMPL_SOLUTION_HEADER("AMPL PROTOTYPE OUTPUT"),
    AMPL_SOLUTION_FOUND("AMPL SOLUTION FOUND"),
    AMPL_FAILED("AMPL FAILED"),
    AMPL_RESULTS("AMPL RESULTS"),

    // Corrective Action result
    CORRECTIVE_ACTION_RESULT("RETURNED CODE");

    private String message;

    IpsoOutputListingMessageType(String message) {
        this.message = message;
    }

    public String getMessage() {
        return this.message;
    }

}
