---
# defaults file for ipst.jdk8

jdk8_url: http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-linux-x64.tar.gz
jdk8_archivename: jdk-8u92-linux-x64.tar.gz
jdk8_dest_path: /opt
jdk8_prefix: "{{ jdk8_dest_path  }}/jdk1.8.0_92"

